version: "3.6"

#volumes:
#  opt_splunk_etc:
#    external: true
#  opt_splunk_var:
#    external: true
volumes:
  - /splunk/etc:/opt/splunk/etc:rwx
  - /splunk/var:/opt/splunk/var:rwx

services:
  splunk:
    image: g3splunk
    restart: always
    privileged: true
    container_name: splunk
    entrypoint: /sbin/g3_entrypoint
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD='cybersecurity'
    ports:
      - 8000:8000
