FROM releases-docker.jfrog.io/jfrog/artifactory-oss:latest
LABEL maintainer="korben@kirscht.com"

#COPY  sbin/g3_entrypoint /sbin/g3_entrypoint
#COPY  etc/sudoers.d/splunk /etc/sudoers.d/splunk
#RUN   sudo chmod +x /sbin/g3_entrypoint