# Install a role from a specific git branch
- name: packages
  src: https://armory.galaxy3.net/vagrant/pkgs

- name: named
  src: https://armory.galaxy3.net/vagrant/ansible_named
  version: named

- name: xrdp
  src: https://armory.galaxy3.net/vagrant/ansible_xrdp
  version: xrdp

- name: week-10-day-2
  src: https://armory.galaxy3.net/vagrant/week-10-day-2

